services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: stockfolio-app
    restart: unless-stopped
    environment:
      - USE_MONGO_DB=true
      - MONGO_URI=mongodb://mongo:27017/stockfolio
    # env_file:
    #  - .env
    networks:
      - stockfolio-network
    depends_on:
      - stockfolio-mongo

  mongo:
    image: mongo:8.0
    container_name: stockfolio-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - stockfolio-network

volumes:
  mongo-data:
    driver: local

networks:
  stockfolio-network:
    driver: bridge
